version: '3.8'

services:
  portfolio:
    container_name: portfolio-react-app
    image: drex422/portfolio-react:latest
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - portfolio

volumes:
  caddy_data:
  caddy_config:
