name: Deploy Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # Solo ejecutar si es un push directo a main o un PR que se ha cerrado (merged)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/portfolio-react:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-react:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-react:buildcache,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 5356
          debug: true
          script: |
            echo "Current directory: $(pwd)"
            echo "Listing directory contents:"
            ls -la
            echo "Checking SSH directory:"
            ls -la ~/.ssh
            echo "Checking authorized_keys:"
            cat ~/.ssh/authorized_keys
            echo "Deploying application..."
            cd ~/portfolio-react
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-react:latest
            docker-compose down
            docker-compose up -d 