name: Deploy Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # Solo ejecutar si es un push directo a main o un PR que se ha cerrado (merged)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: drex422/portfolio-react:latest
          cache-from: type=registry,ref=drex422/portfolio-react:buildcache
          cache-to: type=registry,ref=drex422/portfolio-react:buildcache,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 5356
          debug: true
          script: |
            echo "Installing Docker Compose if not present..."
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found. Installing..."
              curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
              ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            fi
            
            echo "Verifying Docker Compose installation..."
            docker-compose --version
            
            echo "Deploying application..."
            cd ~/portfolio-react
            
            echo "Pulling latest changes from git..."
            git pull origin main
            
            echo "Checking what's using ports 80 and 443..."
            lsof -i :80 || true
            lsof -i :443 || true
            netstat -tulpn | grep :80 || true
            netstat -tulpn | grep :443 || true
            
            echo "Stopping any existing web server..."
            systemctl stop nginx || true
            systemctl stop apache2 || true
            systemctl stop httpd || true
            
            echo "Force stopping and removing existing containers..."
            docker-compose down --remove-orphans --volumes --timeout 30 || true
            
            echo "Force removing any existing containers with the same name..."
            docker rm -f portfolio-react-app || true
            docker rm -f caddy || true
            docker rm -f $(docker ps -aq --filter name=portfolio-react-app) || true
            docker rm -f $(docker ps -aq --filter name=caddy) || true
            
            echo "Cleaning up any dangling containers..."
            docker container prune -f
            
            echo "Building Docker images..."
            docker-compose build --no-cache
            
            echo "Starting new containers..."
            docker-compose up -d --force-recreate --remove-orphans
            
            echo "Waiting for containers to start..."
            sleep 10
            
            echo "Verifying containers are running..."
            docker ps | grep portfolio-react-app
            docker ps | grep caddy
            
            echo "Checking container logs..."
            docker logs portfolio-react-app --tail 10
            docker logs caddy --tail 10
            
            echo "Checking if ports are now available..."
            netstat -tulpn | grep :80 || true
            netstat -tulpn | grep :443 || true
            
            echo "Testing if the application is responding..."
            curl -I http://localhost || true
            curl -I https://localhost || true